#!/bin/bash

clear
echo " "
echo "Build a N1MM Dashboard V1.0"
echo " "

echo "BBBB   U  U  IIIII  LL    DDDD    IIIII N     N  GGGG"
echo "B   B  U  U    I    LL    D   D     I   NN    N G    G"
echo "B   B  U  U    I    LL    D    D    I   N N   N G"
echo "BBBB   U  U    I    LL    D    D    I   N  N  N G GGG"
echo "B   B  U  U    I    LL    D    D    I   N   N N G    G"
echo "B   B  U  U    I    LL    D   D     I   N    N  G    G"
echo "BBBB   UUUU  IIIII  LLLLL DDDD    IIIII N     N  GGGG"
echo " "


echo "N    N   11  M      M M       M"
echo "N N  N   11  MM    MM MM     MM"
echo "N  N N   11  M M  M M M M  M M"
echo "N   NN   11  M  MM  M M  MM  M"
echo "N    N   11  M      M M      M"
echo " "

echo "DDDD        AA     SSSSS  H   H  BBBB    OOO      AA   RRRR   DDDD"
echo "D   D      A  A    S    S H   H  B   B  O   O    A  A  R   R  D   D"
echo "D    D    A    A   S      H   H  B   B  O   O   A    A R   R  D    D"
echo "D    D    AAAAAA   SSSSSS HHHHH  BBBB   O   O   AAAAAA RRRR   D    D"
echo "D    D    A     A       S H   H  B   B  O   o   A    A R   R  D    D"
echo "D   D     A     A  S    S H   H  B   B  O   O   A    A R   R  D   D"
echo "DDDD      A     A  SSSSS  H   H  BBBB    OOO    A    A R   R  DDDD"

echo " "
echo "Press any key to continue"
read
clear  
echo "Installing upgrade"
sudo apt update && sudo apt full-upgrade -y && sudo apt clean
clear
echo " "
sudo apt install build-essential git curl
echo "Press any key to continue"
read
bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered) 
echo "Press any key to continue"
read

sleep 2

echo "Starting node-red"
sudo  systemctl start nodered.service


echo "Enabling node-red restart"
sudo systemctl enable nodered.service
sleep 2
clear
echo " "
echo "Adding nodes"
sleep 2
cd /home/pi/.node-red

npm install node-red-contrib-msg-resend >npmlog.txt
npm install node-red-contrib-binary >>npmlog.txt
npm install node-red-contrib-convert >>npmlog.txt
npm install node-red-contrib-counter >>npmlog.txt
npm install node-red-contrib-image-tools >>npmlog.txt
npm install node-red-contrib-os >>npmlog.txt
npm install Node-red-contrib-streamdeck-ws >>npmlog.txt
npm install node-red-contrib-ui-led >>npmlog.txt
npm install node-red-contrib-ui-level >>npmlog.txt
npm install node-red-contrib-ui-media >>npmlog.txt
npm install node-red-node-ui-list >>npmlog.txt
npm install node-red-dashboard >>npmlog.txt
npm install node-red-node-wol >>npmlog.txt
npm install node-red-contrib-string >>npmlog.txt
npm install node-red-contrib-ui-svg >>npmlog.txt 
npm install node-red-contrib-simple-gate >>npmlog.txt
npm install node-red-contrib-flexradio >>npmlog.txt
npm install node-red-contrib-stoptimer2 >>npmlog.txt
npm install node-red-contrib-startup-trigger >>npmlog.txt
npm install node-red-contrib-ui-digital-display >>npmlog.txt
npm install node-red-contrib-ui-digital-clock >>npmlog.txt
clear
echo "Time to reboot the pi"
echo "Press any key to continue"
read
sudo shutdown -r now



